### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dluman**
Adding course contract for approval by neighborhood members.

### CODE REVIEW

**Comment by dluman** [comment]
Add:

* Tyler
* Morgan
* Josh
* Alinah
* Anton
* Trian

**Review by hameda-1 — APPROVED** [review]
Looks good!

**Comment by josheiser** [comment]
I approve : )

**Comment by leshniowsky01** [comment]
Looks good to me!

**Review by leshniowsky01 — COMMENTED** [review]
Looks good to me! (Sorry if this is showing multiple times)

**Review by Shnacko — COMMENTED** [review]
Looks good!

**Review by ahedlund01 — COMMENTED** [review]
Looks good!

**Pull request merged**
